windows builds
conda-forge/shogun-cpp-feedstock pull request #11
Opened 2017-11-28 22:44 UTC by dougalsutherland

2017-11-28 22:44 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found some lint.

Here's what I've got...


For **recipe**:

 * Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form.see lines [63]

2017-11-28 22:45 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found some lint.

Here's what I've got...


For **recipe**:

 * Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form.see lines [61]

2017-11-28 23:02 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2017-11-28 23:19 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I was trying to look for recipes to lint for you, but it appears we have a merge conflict.
Please try to merge or rebase with the base branch to resolve this conflict.

Please ping the 'conda-forge/core' team (using the @ notation in a comment) if you believe this is a bug.

2017-11-28 23:20 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2017-11-29 02:45 UTC, vigsterkr commented on recipe/meta.yaml
> +    - cmake --build . --target install -config Release  # [win]
it's `--config` with double-dash

2017-11-29 02:48 UTC, vigsterkr requested changes

2017-11-29 02:48 UTC, vigsterkr commented on recipe/meta.yaml
> +          -DLICENSE_GPL_SHOGUN=ON ^                    # [win]
not necessary anymore with 6.1.1

2017-11-29 02:48 UTC, vigsterkr commented on recipe/meta.yaml
> +          -DLIBSHOGUN_BUILD_STATIC=ON                  # [win]
not necessary anymore with 6.1.1

2017-11-29 02:48 UTC, vigsterkr commented on recipe/meta.yaml
> +    - cmake --build . --target install -config Release  # [win]
`--config`

2017-11-29 03:22 UTC, vigsterkr commented on recipe/meta.yaml
> +    - msbuild src\\shogun\\libshogun.vcxproj           # [win]
add the configuration `Release`:
```
msbuild /p:Configuration=Release src\\shogun\\libshogun.vcxproj
```

2017-11-29 03:23 UTC, vigsterkr commented on recipe/meta.yaml
> +    - msbuild src\\shogun\\shogun.vcxproj              # [win]
```msbuild /p:Configuration=Release src\\shogun\\shogun.vcxproj```

2017-11-29 03:23 UTC, vigsterkr commented on recipe/meta.yaml
> +    - msbuild src\\shogun\\shogun-static.vcxproj       # [win]
```
msbuild /p:Configuration=Release src\\shogun\\shogun-static.vcxproj
```

2017-11-29 03:23 UTC, vigsterkr commented on recipe/meta.yaml
> +    - msbuild shogun.sln                               # [win]
```
msbuild /p:Configuration=Release shogun.sln
```

2017-11-29 07:50 UTC, vigsterkr commented
ok the error is because of the `minimal`: https://ci.appveyor.com/project/conda-forge/shogun-cpp-feedstock/build/1.0.13#L16958
```
  CMake Error at examples/minimal/cmake_install.cmake:36 (file):
    file INSTALL cannot find
    "C:/bld/shogun-cpp_1511924007359/work/shogun-shogun_6.1.1/build/examples/minimal/minimal".
  Call Stack (most recent call first):
    cmake_install.cmake:38 (include)
```

2017-11-29 08:06 UTC, vigsterkr commented
this should fix the issue:
https://github.com/shogun-toolbox/shogun/commit/93a64bdca066aa8320f0f468536014422a614b00

2017-11-29 08:30 UTC, vigsterkr commented
ok i've created 6.1.2 release as i've messed up the commits in this early morning a bit :)

2017-11-29 09:29 UTC, djsutherland commented
@vigsterkr Okay, trying again....

btw the Python interface of 6.1.1 is up for Linux and should be up for Mac in a few minutes.

2017-11-29 10:10 UTC, vigsterkr commented
@dougalsutherland hehe yueah i know i've been using the linux version for the last couple of hours ;) thnx heaps!

2017-11-29 11:02 UTC, vigsterkr commented
@dougalsutherland the test is not good for windows:
```
(C:\bld\shogun-cpp_1511949224412\_t_env) (root) C:\bld\shogun-cpp_1511949224412\test_tmp>python -c "import os, ctypes; ctypes.cdll[os.path.join(os.environ['LIBRARY_LIB'], 'libshogun.dylib')]" ```

this definitely will not work - no matter what - on win32 :)
do you need such test when you just build the libshogun itself (that's not yet the python interface). anyhow i dont see the shogun.dll being installed so that might be a problem in the future :)

2017-11-29 11:11 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found some lint.

Here's what I've got...


For **recipe**:

 * Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form.see lines [143]

2017-11-29 11:13 UTC, dougalsutherland commented
I screwed up the test at the very end, but seems to have worked until then, so going ahead and merging.

![leap of faith](https://media.giphy.com/media/38qdhimmpYhOM/giphy.gif)

2017-11-29 11:13 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2017-11-29 11:14 UTC, merged

2017-11-29 11:18 UTC, vigsterkr commented
@dougalsutherland hihi :)

2017-11-29 11:21 UTC, dougalsutherland commented
Have a Windows PR ready to go for shogun-feedstock too, just waiting on shogun-cpp to build.